- Salvage of old Java stuff for use in EHC. Can be turned on with ./configure --enable-java, if a java compiler (named 'javac') is available.   Is based on old library for java laziness, called 'jazy'. For now only most of the framework is in place, only variant 8, only an Int constant can be evaluated.   Old stuff in Core/ToJava, new version in Core/ToJazy, code generation based on Core (not grin).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -667,6 +667,11 @@ EH_VERSION_MINORMINOR
 EH_VERSION_STABILITY
 EH_VERSION_SHORT
 EH_VERSION_FULL
+ENABLE_JAVA
+javacCmd
+jarCmd
+JAVAC_CMD
+JAR_CMD
 ranlibCmd
 RANLIB_CMD
 arCmd
@@ -1326,6 +1331,11 @@ if test -n "$ac_init_help"; then
      short | recursive ) echo "Configuration of EH 0.1:";;
    esac
   cat <<\_ACEOF
+
+Optional Features:
+  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
+  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --enable-java           include java code generation
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1997,6 +2007,137 @@ EH_VERSION_FULL=$EH_VERSION_MAJOR.$EH_VERSION_MINOR.$EH_VERSION_MINORMINOR.$EH_V
 
 
 
+
+### enable options
+# Check whether --enable-java was given.
+if test "${enable_java+set}" = set; then
+  enableval=$enable_java; enableJava=yes
+else
+  enableJava=no
+fi
+
+ENABLE_JAVA=$enableJava
+
+if test x$enableJava == xyes
+then
+
+  # Extract the first word of "javac", so it can be a program name with args.
+set dummy javac; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_javacCmd+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $javacCmd in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_javacCmd="$javacCmd" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_javacCmd="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+javacCmd=$ac_cv_path_javacCmd
+if test -n "$javacCmd"; then
+  { echo "$as_me:$LINENO: result: $javacCmd" >&5
+echo "${ECHO_T}$javacCmd" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  if test -z "$javacCmd"; then
+
+  { { echo "$as_me:$LINENO: error:
+     You must install javac before you can continue
+     Perhaps it is already installed, but not in your PATH?" >&5
+echo "$as_me: error:
+     You must install javac before you can continue
+     Perhaps it is already installed, but not in your PATH?" >&2;}
+   { (exit 1); exit 1; }; }
+
+  fi
+
+
+  # Extract the first word of "jar", so it can be a program name with args.
+set dummy jar; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_jarCmd+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $jarCmd in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_jarCmd="$jarCmd" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_jarCmd="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+jarCmd=$ac_cv_path_jarCmd
+if test -n "$jarCmd"; then
+  { echo "$as_me:$LINENO: result: $jarCmd" >&5
+echo "${ECHO_T}$jarCmd" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  if test -z "$jarCmd"; then
+
+  { { echo "$as_me:$LINENO: error:
+     You must install jar before you can continue
+     Perhaps it is already installed, but not in your PATH?" >&5
+echo "$as_me: error:
+     You must install jar before you can continue
+     Perhaps it is already installed, but not in your PATH?" >&2;}
+   { (exit 1); exit 1; }; }
+
+  fi
+
+  if test "$javacCmd" = "no"; then
+    javacCmd=""
+    jarCmd=""
+    javacExists="no"
+  else
+    javacExists="yes"
+  fi
+  JAVAC_CMD=$javacCmd
+
+  JAR_CMD=$jarCmd
+
+fi
 
 ### ar, ranlib, libtool
 
@@ -7271,6 +7412,11 @@ EH_VERSION_MINORMINOR!$EH_VERSION_MINORMINOR$ac_delim
 EH_VERSION_STABILITY!$EH_VERSION_STABILITY$ac_delim
 EH_VERSION_SHORT!$EH_VERSION_SHORT$ac_delim
 EH_VERSION_FULL!$EH_VERSION_FULL$ac_delim
+ENABLE_JAVA!$ENABLE_JAVA$ac_delim
+javacCmd!$javacCmd$ac_delim
+jarCmd!$jarCmd$ac_delim
+JAVAC_CMD!$JAVAC_CMD$ac_delim
+JAR_CMD!$JAR_CMD$ac_delim
 ranlibCmd!$ranlibCmd$ac_delim
 RANLIB_CMD!$RANLIB_CMD$ac_delim
 arCmd!$arCmd$ac_delim
@@ -7311,11 +7457,6 @@ CPP_CMD!$CPP_CMD$ac_delim
 llvmAs!$llvmAs$ac_delim
 LLVM_AS_CMD!$LLVM_AS_CMD$ac_delim
 llvmOpt!$llvmOpt$ac_delim
-LLVM_OPT_CMD!$LLVM_OPT_CMD$ac_delim
-llvmLlc!$llvmLlc$ac_delim
-LLVM_LLC_CMD!$LLVM_LLC_CMD$ac_delim
-CPP!$CPP$ac_delim
-GREP!$GREP$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -7357,6 +7498,11 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LLVM_OPT_CMD!$LLVM_OPT_CMD$ac_delim
+llvmLlc!$llvmLlc$ac_delim
+LLVM_LLC_CMD!$LLVM_LLC_CMD$ac_delim
+CPP!$CPP$ac_delim
+GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 MACH_DEP_C_FOR_TAILCALL_ENTER!$MACH_DEP_C_FOR_TAILCALL_ENTER$ac_delim
 MACH_DEP_C_FOR_TAILCALL_LEAVE1!$MACH_DEP_C_FOR_TAILCALL_LEAVE1$ac_delim
@@ -7393,7 +7539,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 34; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 39; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -7839,6 +7985,14 @@ echo "  ghc is available?             : $ghcExists"
 if test "x$ghcExists" = "xyes" ;then
 echo "    version                     : $ghcVersion"
 echo "    command for ghc             : $ghcCmd"
+fi
+
+if test x$enableJava == xyes
+then
+  echo "  javac is available?           : $javacExists"
+  if test "x$javacExists" = "xyes" ;then
+  echo "    command for javac           : $javacCmd"
+  fi
 fi
 
 echo "Optional:"
