- Adapted internal interface for GC, so C backend can better hook in. - First version of use of LibTomMath (LTM) instead of GMP. This decreases GC complexity (allocation overhead, use of finalization) and decreases UHC build time/dependencies. Results in better performance unless Integer intensive arithmetic is done. Untested on various platforms. The library is configured as default, GMP can be switched back to at configure time.
WARNING: rerun ./configure

diff --git a/EHC/configure b/EHC/configure
--- a/EHC/configure
+++ b/EHC/configure
@@ -667,6 +667,7 @@ EH_VERSION_MINORMINOR
 EH_VERSION_STABILITY
 EH_VERSION_SHORT
 EH_VERSION_FULL
+m4Cmd
 svnCmd
 SVN_EXISTS
 SVN_CMD
@@ -732,6 +733,8 @@ GREP
 EGREP
 GCC_EXTLIBS_OPTIONS
 GMP_ABI
+MPLIB
+GMP_LIB_ARCHIVE
 MACH_DEP_C_FOR_TAILCALL_ENTER
 MACH_DEP_C_FOR_TAILCALL_LEAVE1
 MACH_DEP_C_FOR_TAILCALL_LEAVE2
@@ -1403,6 +1406,11 @@ Optional Packages:
                           Path to the LLVM bitcode optimizer
   --with-llc=<LLVM Compiler>
                           Path to the LLVM Compiler
+  --with-mplib=ltm|gmp    Specify which MP library to use. Default is ltm
+                          (builtin derivative of LibTomMath).
+  --with-gmplibarchive=<gmp lib archive>
+                          If GMP is used, specify absolute location of GMP
+                          archive (named like .../gmp-X.Y.Z.tar.gz).
 
 Some influential environment variables:
   CC          C compiler command
@@ -2028,6 +2036,61 @@ EH_VERSION_FULL=$EH_VERSION_MAJOR.$EH_VERSION_MINOR.$EH_VERSION_MINORMINOR
 
 
 
+### obvious utils which are amiss on some platforms: m4
+
+  # Extract the first word of "m4", so it can be a program name with args.
+set dummy m4; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_m4Cmd+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $m4Cmd in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_m4Cmd="$m4Cmd" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_m4Cmd="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+m4Cmd=$ac_cv_path_m4Cmd
+if test -n "$m4Cmd"; then
+  { echo "$as_me:$LINENO: result: $m4Cmd" >&5
+echo "${ECHO_T}$m4Cmd" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  if test -z "$m4Cmd"; then
+
+  { { echo "$as_me:$LINENO: error:
+     You must install m4 before you can continue
+     Perhaps it is already installed, but not in your PATH?" >&5
+echo "$as_me: error:
+     You must install m4 before you can continue
+     Perhaps it is already installed, but not in your PATH?" >&2;}
+   { (exit 1); exit 1; }; }
+
+  fi
+
+
 ### svn log/history
 # Extract the first word of "svn", so it can be a program name with args.
 set dummy svn; ac_word=$2
@@ -2072,7 +2135,7 @@ fi
 if test -x "$svnCmd"
 then
   svnExists="yes"
-  $svnCmd log -rHEAD:1 --limit 100 > SVNLOG
+  ### $svnCmd log -rHEAD:1 --limit 100 > SVNLOG
 else
   svnExists="no"
 fi
@@ -28745,11 +28808,60 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
-# Use GMP
+# which MP library
+
+# Check whether --with-mplib was given.
+if test "${with_mplib+set}" = set; then
+  withval=$with_mplib;  mplib="$withval"
+else
+   mplib="ltm"
+
+fi
+
+MPLIB=$mplib
+
+
+# Use GMP or LTM
+if test "$mplib" = "gmp" ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_GMP 1
 _ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_LTM 0
+_ACEOF
+
+else
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_GMP 0
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_LTM 1
+_ACEOF
+
+fi
+
+# which GMP archive
+
+# Check whether --with-gmplibarchive was given.
+if test "${with_gmplibarchive+set}" = set; then
+  withval=$with_gmplibarchive;  gmpLibArchive="$withval"
+else
+   gmpLibArchive=`pwd`/"extlibs/gmp/gmp-4.2.1.tar.gz"
+
+fi
+
+if test -r "$gmpLibArchive" ; then
+  gmpLibArchiveExists="yes"
+else
+  gmpLibArchiveExists="no"
+fi
+GMP_LIB_ARCHIVE="$gmpLibArchive"
 
 
 # Prefix used for global values, assumed to be present by RTS
@@ -29651,6 +29763,7 @@ EH_VERSION_MINORMINOR!$EH_VERSION_MINORMINOR$ac_delim
 EH_VERSION_STABILITY!$EH_VERSION_STABILITY$ac_delim
 EH_VERSION_SHORT!$EH_VERSION_SHORT$ac_delim
 EH_VERSION_FULL!$EH_VERSION_FULL$ac_delim
+m4Cmd!$m4Cmd$ac_delim
 svnCmd!$svnCmd$ac_delim
 SVN_EXISTS!$SVN_EXISTS$ac_delim
 SVN_CMD!$SVN_CMD$ac_delim
@@ -29695,7 +29808,6 @@ gccCmd!$gccCmd$ac_delim
 GCC_CMD!$GCC_CMD$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
-LDFLAGS!$LDFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -29737,6 +29849,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LDFLAGS!$LDFLAGS$ac_delim
 CPPFLAGS!$CPPFLAGS$ac_delim
 ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
@@ -29757,6 +29870,8 @@ GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 GCC_EXTLIBS_OPTIONS!$GCC_EXTLIBS_OPTIONS$ac_delim
 GMP_ABI!$GMP_ABI$ac_delim
+MPLIB!$MPLIB$ac_delim
+GMP_LIB_ARCHIVE!$GMP_LIB_ARCHIVE$ac_delim
 MACH_DEP_C_FOR_TAILCALL_ENTER!$MACH_DEP_C_FOR_TAILCALL_ENTER$ac_delim
 MACH_DEP_C_FOR_TAILCALL_LEAVE1!$MACH_DEP_C_FOR_TAILCALL_LEAVE1$ac_delim
 MACH_DEP_C_FOR_TAILCALL_LEAVE2!$MACH_DEP_C_FOR_TAILCALL_LEAVE2$ac_delim
@@ -29793,7 +29908,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 54; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 57; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -30282,6 +30397,15 @@ then
   echo "  javac is available?           : $javacExists"
   if test "x$javacExists" = "xyes" ;then
   echo "    command for javac           : $javacCmd"
+  fi
+fi
+
+echo "  MP library                    : $mplib"
+if test "$mplib" == "gmp" ; then
+  if test "x$gmpLibArchiveExists" = "xyes" ;then
+    echo "    gmp lib archive             : $gmpLibArchive"
+  else
+    echo "    **** ERROR **** : GMP lib archive not readable: $gmpLibArchive"
   fi
 fi
 
