fixing debugging stuff for type checker, fix for type pretty print which did incorrectly print tyvars

diff --git a/EHC/configure b/EHC/configure
--- a/EHC/configure
+++ b/EHC/configure
@@ -2827,6 +2827,11 @@ EH_VERSION_FULL=$EH_VERSION_MAJOR.$EH_VERSION_MINOR.$EH_VERSION_MINORMINOR.$EH_V
 EH_VERSION_ASNUMBER=$EH_VERSION_MAJOR$EH_VERSION_MINOR_ZEROPAD$EH_VERSION_MINORMINOR_ZEROPAD$EH_VERSION_MINORMINORMINOR_ZEROPAD
 
 
+### global settings, variables, defaults
+# command/msg to run when tool is absent
+cmdForExitIfAbsentLibOrTool='echo "**** ERROR **** : A tool or library is missing. Check ./configure summary." ; exit 1'
+
+
 
 
 
@@ -4288,7 +4293,7 @@ if test "$rulerCmd" != "no" -a -x "$rulerCmd" ; then
   rulerVersion=`$rulerCmd --version`
   buildOptionalToolDependenciesUnchecked="ruler>=0.4.0.1 ${buildOptionalToolDependenciesUnchecked}"
 else
-  rulerCmd=""
+  rulerCmd="${cmdForExitIfAbsentLibOrTool}"
   rulerExists="no"
 fi
 RULER_CMD=$rulerCmd
@@ -9178,7 +9183,7 @@ if test "x$uuagcExists" = "xyes" \
 then
   exitIfAbsentLibOrTool=""
 else
-  exitIfAbsentLibOrTool='echo "**** ERROR **** : A tool or library is missing. Check ./configure summary." ; exit 1'
+  exitIfAbsentLibOrTool="${cmdForExitIfAbsentLibOrTool}"
 fi
 EXIT_IF_ABSENT_LIB_OR_TOOL=$exitIfAbsentLibOrTool
 
@@ -10592,6 +10597,11 @@ echo "  haddock is available?         : $haddockExists"
 if test "x$haddockExists" = "xyes" ;then
 echo "    version                     : $haddockVersion"
 echo "    command for haddock         : $haddockCmd"
+fi
+echo "  ruler is available?           : $rulerExists"
+if test "x$rulerExists" = "xyes" ;then
+echo "    version                     : $rulerVersion"
+echo "    command for ruler           : $rulerCmd"
 fi
 
 echo "Absolute location of directories:"
